root: true

ignorePatterns:
  - 'coverage'
  - 'dist'
  - 'node_modules'
  - 'public'
  - 'pnpm-lock.yaml'
  - '**/__vite*'

env:
  browser: true
  es2022: true
  es6: true
  node: true

parserOptions:
  ecmaVersion: latest
  sourceType: module

extends:
  - '@vue/typescript/recommended'
  - 'standard'
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:cypress/recommended'
  - 'plugin:eslint-comments/recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
  - 'plugin:jsonc/recommended-with-jsonc'
  - 'plugin:markdown/recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:promise/recommended'
  - 'plugin:unicorn/recommended'
  - 'plugin:vue/vue3-recommended'
  - 'plugin:vue-scoped-css/vue3-recommended'
  - 'plugin:yml/standard'
  - 'plugin:yml/prettier'

plugins:
  - 'html'
  - 'import'
  - 'n'
  - 'promise'
  - 'unicorn'
  - 'unused-imports'

rules:
  'no-console': warn
  'no-debugger': warn

  'camelcase': off
  'curly':
    - error
    - all

  'import/order':
    - warn
    - groups:
        - builtin
        - external
        - sibling
        - index
        - internal
        - type
      pathGroups:
        # assets
        - group: builtin
          pattern: '~/assets/**'
          position: before
        # components
        - group: builtin
          pattern: '**/*.vue'
          position: before
        - group: builtin
          pattern: './**/*.vue'
          position: before
        # stores
        - group: external
          pattern: '~/stores/**'
          position: after
        # composables
        - group: external
          pattern: '~/composables/**'
          position: after
        # api
        - group: external
          pattern: '~/api/**'
          position: after
        # helpers
        - group: external
          pattern: '~/helpers/**'
          position: after
      alphabetize:
        order: asc
        caseInsensitive: false
      newlines-between: always

  'promise/prefer-await-to-then': error

  'unicorn/explicit-length-check': off
  'unicorn/no-null': off
  'unicorn/prevent-abbreviations': off

  'vue/component-tags-order':
    - error
    - order:
        - route
        - script
        - template
        - style

  'vue/html-self-closing':
    - warn
    - html:
        component: always
        normal: always
        void: always
      svg: always

  # The code below is necessary for some deps to work properly.
  # Therefore, it is not recommended to modify it.
  # - Vue
  'import/no-unresolved': off
  'no-undef': off
  'no-unmodified-loop-condition': off
  'unicorn/consistent-function-scoping': off
  'unicorn/filename-case': off
  'vue/multi-word-component-names': off

  # - Vue (Reactivity Transform)
  'vue/no-setup-props-destructure': off

  # - Vite
  '@typescript-eslint/consistent-type-imports':
    - error
    - prefer: type-imports
      disallowTypeAnnotations: true

  # - Prettier
  'prettier/prettier': warn
  'vue/max-attributes-per-line': off
  'vue/singleline-html-element-content-newline': off

  # - ESlint
  'yml/plain-scalar': off

  # - eslint-plugin-unused-imports
  '@typescript-eslint/no-unused-vars': off
  'unused-imports/no-unused-imports': error
  'unused-imports/no-unused-vars':
    - warn
    - vars: all
      varsIgnorePattern: ^_
      args: after-used
      argsIgnorePattern: ^_

overrides:
  - files: '*.vue'
    parser: 'vue-eslint-parser'
    parserOptions:
      parser: '@typescript-eslint/parser'

  - files: '*.ts'
    excludedFiles: 'cypress/**/*.spec.ts'
    parserOptions:
      project: 'tsconfig.json'
    rules:
      '@typescript-eslint/consistent-type-exports':
        - error
        - fixMixedExportsWithInlineTypeSpecifier: true

  - files:
      - '*.json'
      - '*.json5'
      - '*.jsonc'
    parser: 'jsonc-eslint-parser'

  - files:
      - '*.yaml'
      - '*.yml'
    parser: 'yaml-eslint-parser'

  - files: '*.test.ts'
    rules:
      '@typescript-eslint/ban-types': off
      '@typescript-eslint/no-empty-function': off
      '@typescript-eslint/no-explicit-any': off

  - files: 'shims.d.ts'
    rules:
      '@typescript-eslint/ban-types': off
      '@typescript-eslint/no-explicit-any': off
